# Generated by Django 3.2.3 on 2021-05-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(max_length=50, unique=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='Cnpj')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, verbose_name='Inscrição municipal')),
                ('telefone', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('site', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('endereco', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('SUSPENSO', 'SUSPENSO'), ('EXCLUIDO', 'EXCLUIDO'), ('NEGATIVADO', 'NEGATIVADO')], max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, max_length=30, verbose_name='Contrato')),
                ('observacoes', models.TextField(blank=True, max_length=250)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ('nome_fantasia',),
            },
        ),
    ]
